# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0003_auto_20170921_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded_books',
            field=models.ManyToManyField(related_name='uploader', to='likes_books.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='likes_books.User'),
        ),
    ]
