# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0004_auto_20170922_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploaded_books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likes_books.User'),
        ),
    ]
